# Generated by Django 3.1.1 on 2020-10-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('demo', models.URLField()),
                ('github', models.URLField()),
                ('tech', models.JSONField()),
            ],
        ),
    ]
