# Generated by Django 3.1.1 on 2020-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201003_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True),
        ),
    ]
